apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: app
  labels:
    app: exercise-10
    component: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
